### ISSUE TITLE
请邀请我成为水系历史骰主并允许我为社区做出贡献

### ISSUE THREAD

**Issue by baimianxiao** [HydroRoll-Team/support#3]
### Name

白咕咕

### QQ ID (if applicable)

HydroRoll-Team

### Additional Context

了解/学习

**Comment by HsiangNianian** [comment]
<b>邀请函发送成功~ 欢迎来到水系社区！ 🎉</b><br><br>不要忘记在人员列表内将组织可见性改成“公开”("Public")，这样可以让所有人都看到。 你可以在[这里](https://github.com/orgs/HydroRoll-Team/people)找到自己并且更改组织可见性。<br>希望这些可以帮助你！<br><br>2023年6月30日 by 简律纯。
