### ISSUE TITLE
请邀请我成为水系历史骰主或加入社区并允许我为社区做出贡献

### ISSUE THREAD

**Issue by HJJmx** [HydroRoll-Team/support#7]
### Name

暮星

### QQ ID (if applicable)

1009592348

### 你想以怎样的身份进入水系社区？（默认：遗产骰主）

遗产骰主

### Additional Context

了解水系的训练模型和ai骰娘

**Comment by HsiangNianian** [comment]
<b>邀请函发送成功~ 欢迎来到水系社区！ 🎉</b><br><br>不要忘记在人员列表内将组织可见性改成“公开”("Public")，这样可以让所有人都看到。 <br>你可以在[这里](https://github.com/orgs/HydroRoll-Team/people)找到自己并且更改组织可见性。<br><br>希望这些可以帮助你！<br><br>简律纯。
